defaults:
  - submitit_slurm

timeout_min: 2880  # 2 days
cpus_per_task: 4
mem_gb: 350
partition: owners,gpu,shenoy
gpus_per_node: 1
setup:
  - ml load cudnn/8.6.0.163
additional_parameters:
  constraint:
  mail-type: ALL
